version: '3.3'

services:
    
  mailhog:
    image: 'mailhog/mailhog'
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    container_name: mailhog
    networks:
      - crispcms
      - default


  adminer:
    image: 'adminer'
    restart: always
    ports:
      - 8080:8080
    container_name: adminer
    networks:
      - crispcms
      - default


  postgres:
    image: 'postgres:14'
    restart: always
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - crispcms
      - default


  crispcms:
    build:
      context: .
    container_name: crispcms
    ports:
      - 80:80
      - 81:81
    links:
      - typesense
    environment:
        - CRISP_THEME=crisptheme
        - VERBOSITY=3
        - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/postgres
        - TZ=Europe/Berlin
        - HOST=${HOST}
        - ROOT=${HOST}
        - PROTO=https
        - SENTRY_DSN=CHANGE_ME
        - ENVIRONMENT=development
        - SENTRY_JS_DSN=CHANGE_ME
        - LANG=de_DE.UTF-8
        - DEFAULT_LOCALE=de

    volumes:
      - crisp:/data
      - ./public:/var/www/crisp/cms/themes/crisptheme
      - ./.env:/var/www/crisp/.env
    networks:
      - crispcms
      - default

networks:
  crispcms:
    name: crispcms
    external: true

volumes:
  crisp:
  postgres: